sudo: false
language: ruby
rvm:
  - '2.5.0'
  - '2.5'
  - '2.6.0'
  - '2.6'

install:
  - gem install bundler -v '~> 1.17.3'
  - gem install rubocop
  - bundle update

script:
  - rubocop
  - rspec spec
